# Generated by Django 4.2.2 on 2023-06-26 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image_generator', '0006_alter_planet_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('planet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='image_generator.planet')),
                ('pub_text', models.TextField(blank=True, max_length=5000, verbose_name='publication text')),
            ],
        ),
    ]
