# Generated by Django 4.2.2 on 2023-06-24 10:18

from django.db import migrations, models
import image_generator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the planet.', max_length=150)),
                ('radius', models.DecimalField(db_column='mean_radius', decimal_places=4, help_text='Mean radius of the planet.', max_digits=11)),
                ('mass', models.DecimalField(decimal_places=5, help_text='Total mass of the planet.', max_digits=10)),
                ('bulk_density', models.DecimalField(decimal_places=4, help_text='Density computed using the total volume and mass of the planet.', max_digits=5)),
                ('albedo', models.DecimalField(decimal_places=4, help_text='\n        Albedo is ratio of the light received by a body to the light reflected by that body.\n        Albedo values range from 0 (pitch black) to 1 (perfect reflector).\n    ', max_digits=5, validators=[image_generator.models.validate_albedo])),
                ('gravity', models.DecimalField(decimal_places=2, help_text="The gravitational acceleration on the planet's surface at the equator.", max_digits=4)),
            ],
        ),
    ]
