# Generated by Django 4.2.2 on 2023-06-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='resolution',
            field=models.CharField(choices=[('256x256', '256x256'), ('512x512', '512x512'), ('1024x1024', '1024x1024')], default='256x256', max_length=16),
        ),
    ]
