# Generated by Django 4.2.2 on 2023-06-25 04:43

from django.db import migrations, models
import image_generator.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_generator', '0002_planet_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='albedo',
            field=models.DecimalField(decimal_places=4, help_text='\n        Albedo is ratio of the light received by a body to the light reflected by that body.\n        Albedo values range from 0 (pitch black) to 1 (perfect reflector).\n    ', max_digits=5, validators=[image_generator.models.validate_positive, image_generator.models.validate_albedo]),
        ),
        migrations.AlterField(
            model_name='planet',
            name='bulk_density',
            field=models.DecimalField(decimal_places=4, help_text='Density computed using the total volume and mass of the planet.', max_digits=5, validators=[image_generator.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='planet',
            name='gravity',
            field=models.DecimalField(decimal_places=2, help_text="The gravitational acceleration on the planet's surface at the equator.", max_digits=4, validators=[image_generator.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='planet',
            name='mass',
            field=models.DecimalField(decimal_places=5, help_text='Total mass of the planet.', max_digits=10, validators=[image_generator.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='planet',
            name='radius',
            field=models.DecimalField(db_column='mean_radius', decimal_places=4, help_text='Mean radius of the planet.', max_digits=11, validators=[image_generator.models.validate_positive]),
        ),
    ]
