# Generated by Django 4.2.2 on 2023-06-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_generator', '0005_planet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='image',
            field=models.ImageField(help_text='Generated image of a planet.', upload_to=''),
        ),
    ]
