# Generated by Django 4.2.2 on 2023-07-01 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('image_generator', '0006_alter_planet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
